g++ -c -o LexA68k.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexA68k.o -MFLexA68k.o.d -MD -MP LexA68k.cxx
g++ -c -o LexAbaqus.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexAbaqus.o -MFLexAbaqus.o.d -MD -MP LexAbaqus.cxx
g++ -c -o LexAda.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexAda.o -MFLexAda.o.d -MD -MP LexAda.cxx
g++ -c -o LexAPDL.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexAPDL.o -MFLexAPDL.o.d -MD -MP LexAPDL.cxx
g++ -c -o LexAsm.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexAsm.o -MFLexAsm.o.d -MD -MP LexAsm.cxx
g++ -c -o LexAsn1.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexAsn1.o -MFLexAsn1.o.d -MD -MP LexAsn1.cxx
g++ -c -o LexASY.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexASY.o -MFLexASY.o.d -MD -MP LexASY.cxx
g++ -c -o LexAU3.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexAU3.o -MFLexAU3.o.d -MD -MP LexAU3.cxx
g++ -c -o LexAVE.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexAVE.o -MFLexAVE.o.d -MD -MP LexAVE.cxx
g++ -c -o LexAVS.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexAVS.o -MFLexAVS.o.d -MD -MP LexAVS.cxx
g++ -c -o LexBaan.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexBaan.o -MFLexBaan.o.d -MD -MP LexBaan.cxx
g++ -c -o LexBash.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexBash.o -MFLexBash.o.d -MD -MP LexBash.cxx
g++ -c -o LexBasic.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexBasic.o -MFLexBasic.o.d -MD -MP LexBasic.cxx
g++ -c -o LexBullant.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexBullant.o -MFLexBullant.o.d -MD -MP LexBullant.cxx
g++ -c -o LexCaml.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexCaml.o -MFLexCaml.o.d -MD -MP LexCaml.cxx
g++ -c -o LexCLW.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexCLW.o -MFLexCLW.o.d -MD -MP LexCLW.cxx
g++ -c -o LexCmake.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexCmake.o -MFLexCmake.o.d -MD -MP LexCmake.cxx
g++ -c -o LexCOBOL.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexCOBOL.o -MFLexCOBOL.o.d -MD -MP LexCOBOL.cxx
g++ -c -o LexCoffeeScript.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexCoffeeScript.o -MFLexCoffeeScript.o.d -MD -MP LexCoffeeScript.cxx
g++ -c -o LexConf.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexConf.o -MFLexConf.o.d -MD -MP LexConf.cxx
g++ -c -o LexCPP.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexCPP.o -MFLexCPP.o.d -MD -MP LexCPP.cxx
g++ -c -o LexCrontab.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexCrontab.o -MFLexCrontab.o.d -MD -MP LexCrontab.cxx
g++ -c -o LexCsound.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexCsound.o -MFLexCsound.o.d -MD -MP LexCsound.cxx
g++ -c -o LexCSS.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexCSS.o -MFLexCSS.o.d -MD -MP LexCSS.cxx
g++ -c -o LexD.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexD.o -MFLexD.o.d -MD -MP LexD.cxx
g++ -c -o LexECL.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexECL.o -MFLexECL.o.d -MD -MP LexECL.cxx
g++ -c -o LexEiffel.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexEiffel.o -MFLexEiffel.o.d -MD -MP LexEiffel.cxx
g++ -c -o LexErlang.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexErlang.o -MFLexErlang.o.d -MD -MP LexErlang.cxx
g++ -c -o LexEScript.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexEScript.o -MFLexEScript.o.d -MD -MP LexEScript.cxx
g++ -c -o LexFlagship.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexFlagship.o -MFLexFlagship.o.d -MD -MP LexFlagship.cxx
g++ -c -o LexForth.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexForth.o -MFLexForth.o.d -MD -MP LexForth.cxx
g++ -c -o LexFortran.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexFortran.o -MFLexFortran.o.d -MD -MP LexFortran.cxx
g++ -c -o LexGAP.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexGAP.o -MFLexGAP.o.d -MD -MP LexGAP.cxx
g++ -c -o LexGui4Cli.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexGui4Cli.o -MFLexGui4Cli.o.d -MD -MP LexGui4Cli.cxx
g++ -c -o LexHaskell.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexHaskell.o -MFLexHaskell.o.d -MD -MP LexHaskell.cxx
g++ -c -o LexHTML.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexHTML.o -MFLexHTML.o.d -MD -MP LexHTML.cxx
g++ -c -o LexInno.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexInno.o -MFLexInno.o.d -MD -MP LexInno.cxx
g++ -c -o LexKix.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexKix.o -MFLexKix.o.d -MD -MP LexKix.cxx
g++ -c -o LexLisp.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexLisp.o -MFLexLisp.o.d -MD -MP LexLisp.cxx
g++ -c -o LexLout.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexLout.o -MFLexLout.o.d -MD -MP LexLout.cxx
g++ -c -o LexLua.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexLua.o -MFLexLua.o.d -MD -MP LexLua.cxx
g++ -c -o LexMagik.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexMagik.o -MFLexMagik.o.d -MD -MP LexMagik.cxx
g++ -c -o LexMarkdown.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexMarkdown.o -MFLexMarkdown.o.d -MD -MP LexMarkdown.cxx
g++ -c -o LexMatlab.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexMatlab.o -MFLexMatlab.o.d -MD -MP LexMatlab.cxx
g++ -c -o LexMetapost.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexMetapost.o -MFLexMetapost.o.d -MD -MP LexMetapost.cxx
g++ -c -o LexMMIXAL.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexMMIXAL.o -MFLexMMIXAL.o.d -MD -MP LexMMIXAL.cxx
g++ -c -o LexModula.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexModula.o -MFLexModula.o.d -MD -MP LexModula.cxx
g++ -c -o LexMPT.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexMPT.o -MFLexMPT.o.d -MD -MP LexMPT.cxx
g++ -c -o LexMSSQL.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexMSSQL.o -MFLexMSSQL.o.d -MD -MP LexMSSQL.cxx
g++ -c -o LexMySQL.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexMySQL.o -MFLexMySQL.o.d -MD -MP LexMySQL.cxx
g++ -c -o LexNimrod.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexNimrod.o -MFLexNimrod.o.d -MD -MP LexNimrod.cxx
g++ -c -o LexNsis.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexNsis.o -MFLexNsis.o.d -MD -MP LexNsis.cxx
g++ -c -o LexOpal.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexOpal.o -MFLexOpal.o.d -MD -MP LexOpal.cxx
g++ -c -o LexOScript.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexOScript.o -MFLexOScript.o.d -MD -MP LexOScript.cxx
g++ -c -o LexOthers.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexOthers.o -MFLexOthers.o.d -MD -MP LexOthers.cxx
g++ -c -o LexPascal.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexPascal.o -MFLexPascal.o.d -MD -MP LexPascal.cxx
g++ -c -o LexPB.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexPB.o -MFLexPB.o.d -MD -MP LexPB.cxx
g++ -c -o LexPerl.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexPerl.o -MFLexPerl.o.d -MD -MP LexPerl.cxx
g++ -c -o LexPLM.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexPLM.o -MFLexPLM.o.d -MD -MP LexPLM.cxx
g++ -c -o LexPOV.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexPOV.o -MFLexPOV.o.d -MD -MP LexPOV.cxx
g++ -c -o LexPowerPro.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexPowerPro.o -MFLexPowerPro.o.d -MD -MP LexPowerPro.cxx
g++ -c -o LexPowerShell.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexPowerShell.o -MFLexPowerShell.o.d -MD -MP LexPowerShell.cxx
g++ -c -o LexProgress.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexProgress.o -MFLexProgress.o.d -MD -MP LexProgress.cxx
g++ -c -o LexPS.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexPS.o -MFLexPS.o.d -MD -MP LexPS.cxx
g++ -c -o LexPython.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexPython.o -MFLexPython.o.d -MD -MP LexPython.cxx
g++ -c -o LexR.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexR.o -MFLexR.o.d -MD -MP LexR.cxx
g++ -c -o LexRebol.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexRebol.o -MFLexRebol.o.d -MD -MP LexRebol.cxx
g++ -c -o LexRuby.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexRuby.o -MFLexRuby.o.d -MD -MP LexRuby.cxx
g++ -c -o LexScriptol.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexScriptol.o -MFLexScriptol.o.d -MD -MP LexScriptol.cxx
g++ -c -o LexSmalltalk.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexSmalltalk.o -MFLexSmalltalk.o.d -MD -MP LexSmalltalk.cxx
g++ -c -o LexSML.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexSML.o -MFLexSML.o.d -MD -MP LexSML.cxx
g++ -c -o LexSorcus.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexSorcus.o -MFLexSorcus.o.d -MD -MP LexSorcus.cxx
g++ -c -o LexSpecman.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexSpecman.o -MFLexSpecman.o.d -MD -MP LexSpecman.cxx
g++ -c -o LexSpice.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexSpice.o -MFLexSpice.o.d -MD -MP LexSpice.cxx
g++ -c -o LexSQL.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexSQL.o -MFLexSQL.o.d -MD -MP LexSQL.cxx
g++ -c -o LexTACL.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexTACL.o -MFLexTACL.o.d -MD -MP LexTACL.cxx
g++ -c -o LexTADS3.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexTADS3.o -MFLexTADS3.o.d -MD -MP LexTADS3.cxx
g++ -c -o LexTAL.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexTAL.o -MFLexTAL.o.d -MD -MP LexTAL.cxx
g++ -c -o LexTCL.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexTCL.o -MFLexTCL.o.d -MD -MP LexTCL.cxx
g++ -c -o LexTCMD.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexTCMD.o -MFLexTCMD.o.d -MD -MP LexTCMD.cxx
g++ -c -o LexTeX.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexTeX.o -MFLexTeX.o.d -MD -MP LexTeX.cxx
g++ -c -o LexTxt2tags.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexTxt2tags.o -MFLexTxt2tags.o.d -MD -MP LexTxt2tags.cxx
g++ -c -o LexVB.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexVB.o -MFLexVB.o.d -MD -MP LexVB.cxx
g++ -c -o LexVerilog.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexVerilog.o -MFLexVerilog.o.d -MD -MP LexVerilog.cxx
g++ -c -o LexVHDL.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexVHDL.o -MFLexVHDL.o.d -MD -MP LexVHDL.cxx
g++ -c -o LexVisualProlog.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexVisualProlog.o -MFLexVisualProlog.o.d -MD -MP LexVisualProlog.cxx
g++ -c -o LexYAML.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexYAML.o -MFLexYAML.o.d -MD -MP LexYAML.cxx
g++ -c -o Accessor.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTAccessor.o -MFAccessor.o.d -MD -MP Accessor.cxx
g++ -c -o CharacterSet.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTCharacterSet.o -MFCharacterSet.o.d -MD -MP CharacterSet.cxx
g++ -c -o LexerBase.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexerBase.o -MFLexerBase.o.d -MD -MP LexerBase.cxx
g++ -c -o LexerModule.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexerModule.o -MFLexerModule.o.d -MD -MP LexerModule.cxx
g++ -c -o LexerNoExceptions.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexerNoExceptions.o -MFLexerNoExceptions.o.d -MD -MP LexerNoExceptions.cxx
g++ -c -o LexerSimple.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLexerSimple.o -MFLexerSimple.o.d -MD -MP LexerSimple.cxx
g++ -c -o PropSetSimple.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTPropSetSimple.o -MFPropSetSimple.o.d -MD -MP PropSetSimple.cxx
g++ -c -o StyleContext.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTStyleContext.o -MFStyleContext.o.d -MD -MP StyleContext.cxx
g++ -c -o WordList.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTWordList.o -MFWordList.o.d -MD -MP WordList.cxx
g++ -c -o AutoComplete.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTAutoComplete.o -MFAutoComplete.o.d -MD -MP AutoComplete.cxx
g++ -c -o CallTip.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTCallTip.o -MFCallTip.o.d -MD -MP CallTip.cxx
g++ -c -o Catalogue.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTCatalogue.o -MFCatalogue.o.d -MD -MP Catalogue.cxx
g++ -c -o CellBuffer.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTCellBuffer.o -MFCellBuffer.o.d -MD -MP CellBuffer.cxx
g++ -c -o CharClassify.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTCharClassify.o -MFCharClassify.o.d -MD -MP CharClassify.cxx
g++ -c -o ContractionState.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTContractionState.o -MFContractionState.o.d -MD -MP ContractionState.cxx
g++ -c -o Decoration.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTDecoration.o -MFDecoration.o.d -MD -MP Decoration.cxx
g++ -c -o Document.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTDocument.o -MFDocument.o.d -MD -MP Document.cxx
g++ -c -o Editor.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTEditor.o -MFEditor.o.d -MD -MP Editor.cxx
g++ -c -o ExternalLexer.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTExternalLexer.o -MFExternalLexer.o.d -MD -MP ExternalLexer.cxx
g++ -c -o Indicator.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTIndicator.o -MFIndicator.o.d -MD -MP Indicator.cxx
g++ -c -o KeyMap.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTKeyMap.o -MFKeyMap.o.d -MD -MP KeyMap.cxx
g++ -c -o LineMarker.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTLineMarker.o -MFLineMarker.o.d -MD -MP LineMarker.cxx
g++ -c -o PerLine.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTPerLine.o -MFPerLine.o.d -MD -MP PerLine.cxx
g++ -c -o PositionCache.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTPositionCache.o -MFPositionCache.o.d -MD -MP PositionCache.cxx
g++ -c -o RESearch.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTRESearch.o -MFRESearch.o.d -MD -MP RESearch.cxx
g++ -c -o RunStyles.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTRunStyles.o -MFRunStyles.o.d -MD -MP RunStyles.cxx
g++ -c -o ScintillaBase.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTScintillaBase.o -MFScintillaBase.o.d -MD -MP ScintillaBase.cxx
g++ -c -o Selection.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTSelection.o -MFSelection.o.d -MD -MP Selection.cxx
g++ -c -o Style.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTStyle.o -MFStyle.o.d -MD -MP Style.cxx
g++ -c -o UniConversion.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTUniConversion.o -MFUniConversion.o.d -MD -MP UniConversion.cxx
g++ -c -o ViewStyle.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTViewStyle.o -MFViewStyle.o.d -MD -MP ViewStyle.cxx
g++ -c -o XPM.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -D__WX__ -DSCI_LEXER -DLINK_LEXERS -D__WXMSW__ -D_UNICODE -MTXPM.o -MFXPM.o.d -MD -MP XPM.cxx