#define SOKOL_WIN32_FORCE_MAIN
#ifndef SOKOL_GLES3
#define SOKOL_GLCORE33
#endif
#include "sokol_app.h"
#include "sokol_args.h"
#include "sokol_audio.h"
#include "sokol_color.h"
#include "sokol_debugtext.h"
#include "sokol_fetch.h"
#include "sokol_fontstash.h"
#include "sokol_gfx.h"
#include "sokol_gfx_imgui.h"
#include "sokol_gl.h"
#include "sokol_glue.h"
#include "sokol_imgui.h"
#include "sokol_log.h"
#include "sokol_memtrack.h"
#include "sokol_nuklear.h"
#include "sokol_shape.h"
#include "sokol_spine.h"
#include "sokol_time.h"
