// Autogenerated by gameplay-luagen
#include "gameplay-Base.h"
#include "gameplay-ScriptController.h"
#include "gameplay-lua_ScriptTargetEvent.h"
#include "gameplay-AnimationClip.h"
#include "gameplay-Base.h"
#include "gameplay-Button.h"
#include "gameplay-CheckBox.h"
#include "gameplay-Container.h"
#include "gameplay-Control.h"
#include "gameplay-Form.h"
#include "gameplay-ImageControl.h"
#include "gameplay-Joint.h"
#include "gameplay-JoystickControl.h"
#include "gameplay-Label.h"
#include "gameplay-Node.h"
#include "gameplay-PhysicsController.h"
#include "gameplay-RadioButton.h"
#include "gameplay-ScriptController.h"
#include "gameplay-ScriptTarget.h"
#include "gameplay-Slider.h"
#include "gameplay-TextBox.h"
#include "gameplay-Transform.h"

namespace gameplay
{

static ScriptTarget::Event* getInstance(lua_State* state)
{
    void* userdata = luaL_checkudata(state, 1, "ScriptTargetEvent");
    luaL_argcheck(state, userdata != NULL, 1, "'ScriptTargetEvent' expected.");
    return (ScriptTarget::Event*)((gameplay::ScriptUtil::LuaObject*)userdata)->instance;
}

static int lua_ScriptTargetEvent__gc(lua_State* state)
{
    // Get the number of parameters.
    int paramCount = lua_gettop(state);

    // Attempt to match the parameters to a valid binding.
    switch (paramCount)
    {
        case 1:
        {
            if ((lua_type(state, 1) == LUA_TUSERDATA))
            {
                void* userdata = luaL_checkudata(state, 1, "ScriptTargetEvent");
                luaL_argcheck(state, userdata != NULL, 1, "'ScriptTargetEvent' expected.");
                gameplay::ScriptUtil::LuaObject* object = (gameplay::ScriptUtil::LuaObject*)userdata;
                if (object->owns)
                {
                    ScriptTarget::Event* instance = (ScriptTarget::Event*)object->instance;
                    SAFE_DELETE(instance);
                }
                
                return 0;
            }

            lua_pushstring(state, "lua_ScriptTargetEvent__gc - Failed to match the given parameters to a valid function signature.");
            lua_error(state);
            break;
        }
        default:
        {
            lua_pushstring(state, "Invalid number of parameters (expected 1).");
            lua_error(state);
            break;
        }
    }
    return 0;
}

static int lua_ScriptTargetEvent__init(lua_State* state)
{
    // Get the number of parameters.
    int paramCount = lua_gettop(state);

    // Attempt to match the parameters to a valid binding.
    switch (paramCount)
    {
        case 0:
        {
            void* returnPtr = ((void*)new ScriptTarget::Event());
            if (returnPtr)
            {
                gameplay::ScriptUtil::LuaObject* object = (gameplay::ScriptUtil::LuaObject*)lua_newuserdata(state, sizeof(gameplay::ScriptUtil::LuaObject));
                object->instance = returnPtr;
                object->owns = true;
                luaL_getmetatable(state, "ScriptTargetEvent");
                lua_setmetatable(state, -2);
            }
            else
            {
                lua_pushnil(state);
            }

            return 1;
            break;
        }
        default:
        {
            lua_pushstring(state, "Invalid number of parameters (expected 0).");
            lua_error(state);
            break;
        }
    }
    return 0;
}

static int lua_ScriptTargetEvent_getArgs(lua_State* state)
{
    // Get the number of parameters.
    int paramCount = lua_gettop(state);

    // Attempt to match the parameters to a valid binding.
    switch (paramCount)
    {
        case 1:
        {
            if ((lua_type(state, 1) == LUA_TUSERDATA))
            {
                ScriptTarget::Event* instance = getInstance(state);
                const char* result = instance->getArgs();

                // Push the return value onto the stack.
                lua_pushstring(state, result);

                return 1;
            }

            lua_pushstring(state, "lua_ScriptTargetEvent_getArgs - Failed to match the given parameters to a valid function signature.");
            lua_error(state);
            break;
        }
        default:
        {
            lua_pushstring(state, "Invalid number of parameters (expected 1).");
            lua_error(state);
            break;
        }
    }
    return 0;
}

static int lua_ScriptTargetEvent_getName(lua_State* state)
{
    // Get the number of parameters.
    int paramCount = lua_gettop(state);

    // Attempt to match the parameters to a valid binding.
    switch (paramCount)
    {
        case 1:
        {
            if ((lua_type(state, 1) == LUA_TUSERDATA))
            {
                ScriptTarget::Event* instance = getInstance(state);
                const char* result = instance->getName();

                // Push the return value onto the stack.
                lua_pushstring(state, result);

                return 1;
            }

            lua_pushstring(state, "lua_ScriptTargetEvent_getName - Failed to match the given parameters to a valid function signature.");
            lua_error(state);
            break;
        }
        default:
        {
            lua_pushstring(state, "Invalid number of parameters (expected 1).");
            lua_error(state);
            break;
        }
    }
    return 0;
}

void luaRegister_ScriptTargetEvent()
{
    const luaL_Reg lua_members[] = 
    {
        {"getArgs", lua_ScriptTargetEvent_getArgs},
        {"getName", lua_ScriptTargetEvent_getName},
        {NULL, NULL}
    };
    const luaL_Reg* lua_statics = NULL;
    std::vector<std::string> scopePath;
    scopePath.push_back("ScriptTarget");

    gameplay::ScriptUtil::registerClass("ScriptTargetEvent", lua_members, lua_ScriptTargetEvent__init, lua_ScriptTargetEvent__gc, lua_statics, scopePath);

}

}
