gcc -c -o jcomapi.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjcomapi.o -MFjcomapi.o.d -MD -MP jcomapi.c
gcc -c -o jutils.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjutils.o -MFjutils.o.d -MD -MP jutils.c
gcc -c -o jerror.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjerror.o -MFjerror.o.d -MD -MP jerror.c
gcc -c -o jmemmgr.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjmemmgr.o -MFjmemmgr.o.d -MD -MP jmemmgr.c
gcc -c -o jmemnobs.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjmemnobs.o -MFjmemnobs.o.d -MD -MP jmemnobs.c
gcc -c -o jcapimin.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjcapimin.o -MFjcapimin.o.d -MD -MP jcapimin.c
gcc -c -o jcapistd.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjcapistd.o -MFjcapistd.o.d -MD -MP jcapistd.c
gcc -c -o jctrans.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjctrans.o -MFjctrans.o.d -MD -MP jctrans.c
gcc -c -o jcparam.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjcparam.o -MFjcparam.o.d -MD -MP jcparam.c
gcc -c -o jdatadst.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjdatadst.o -MFjdatadst.o.d -MD -MP jdatadst.c
gcc -c -o jcinit.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjcinit.o -MFjcinit.o.d -MD -MP jcinit.c
gcc -c -o jcmaster.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjcmaster.o -MFjcmaster.o.d -MD -MP jcmaster.c
gcc -c -o jcmarker.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjcmarker.o -MFjcmarker.o.d -MD -MP jcmarker.c
gcc -c -o jcmainct.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjcmainct.o -MFjcmainct.o.d -MD -MP jcmainct.c
gcc -c -o jcprepct.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjcprepct.o -MFjcprepct.o.d -MD -MP jcprepct.c
gcc -c -o jccoefct.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjccoefct.o -MFjccoefct.o.d -MD -MP jccoefct.c
gcc -c -o jccolor.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjccolor.o -MFjccolor.o.d -MD -MP jccolor.c
gcc -c -o jcsample.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjcsample.o -MFjcsample.o.d -MD -MP jcsample.c
gcc -c -o jchuff.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjchuff.o -MFjchuff.o.d -MD -MP jchuff.c
gcc -c -o jcphuff.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjcphuff.o -MFjcphuff.o.d -MD -MP jcphuff.c
gcc -c -o jcdctmgr.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjcdctmgr.o -MFjcdctmgr.o.d -MD -MP jcdctmgr.c
gcc -c -o jfdctfst.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjfdctfst.o -MFjfdctfst.o.d -MD -MP jfdctfst.c
gcc -c -o jfdctflt.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjfdctflt.o -MFjfdctflt.o.d -MD -MP jfdctflt.c
gcc -c -o jfdctint.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjfdctint.o -MFjfdctint.o.d -MD -MP jfdctint.c
gcc -c -o jdapimin.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjdapimin.o -MFjdapimin.o.d -MD -MP jdapimin.c
gcc -c -o jdapistd.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjdapistd.o -MFjdapistd.o.d -MD -MP jdapistd.c
gcc -c -o jdtrans.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjdtrans.o -MFjdtrans.o.d -MD -MP jdtrans.c
gcc -c -o jdatasrc.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjdatasrc.o -MFjdatasrc.o.d -MD -MP jdatasrc.c
gcc -c -o jdmaster.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjdmaster.o -MFjdmaster.o.d -MD -MP jdmaster.c
gcc -c -o jdinput.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjdinput.o -MFjdinput.o.d -MD -MP jdinput.c
gcc -c -o jdmarker.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjdmarker.o -MFjdmarker.o.d -MD -MP jdmarker.c
gcc -c -o jdhuff.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjdhuff.o -MFjdhuff.o.d -MD -MP jdhuff.c
gcc -c -o jdphuff.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjdphuff.o -MFjdphuff.o.d -MD -MP jdphuff.c
gcc -c -o jdmainct.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjdmainct.o -MFjdmainct.o.d -MD -MP jdmainct.c
gcc -c -o jdcoefct.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjdcoefct.o -MFjdcoefct.o.d -MD -MP jdcoefct.c
gcc -c -o jdpostct.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjdpostct.o -MFjdpostct.o.d -MD -MP jdpostct.c
gcc -c -o jddctmgr.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjddctmgr.o -MFjddctmgr.o.d -MD -MP jddctmgr.c
gcc -c -o jidctfst.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjidctfst.o -MFjidctfst.o.d -MD -MP jidctfst.c
gcc -c -o jidctflt.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjidctflt.o -MFjidctflt.o.d -MD -MP jidctflt.c
gcc -c -o jidctint.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjidctint.o -MFjidctint.o.d -MD -MP jidctint.c
gcc -c -o jidctred.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjidctred.o -MFjidctred.o.d -MD -MP jidctred.c
gcc -c -o jdsample.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjdsample.o -MFjdsample.o.d -MD -MP jdsample.c
gcc -c -o jdcolor.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjdcolor.o -MFjdcolor.o.d -MD -MP jdcolor.c
gcc -c -o jquant1.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjquant1.o -MFjquant1.o.d -MD -MP jquant1.c
gcc -c -o jquant2.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjquant2.o -MFjquant2.o.d -MD -MP jquant2.c
gcc -c -o jdmerge.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG    -MTjdmerge.o -MFjdmerge.o.d -MD -MP jdmerge.c