gcc -c -o tif_win32.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_win32.o -MFtif_win32.o.d -MD -MP tif_win32.c
gcc -c -o tif_aux.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_aux.o -MFtif_aux.o.d -MD -MP tif_aux.c
gcc -c -o tif_close.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_close.o -MFtif_close.o.d -MD -MP tif_close.c
gcc -c -o tif_codec.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_codec.o -MFtif_codec.o.d -MD -MP tif_codec.c
gcc -c -o tif_color.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_color.o -MFtif_color.o.d -MD -MP tif_color.c
gcc -c -o tif_compress.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_compress.o -MFtif_compress.o.d -MD -MP tif_compress.c
gcc -c -o tif_dir.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_dir.o -MFtif_dir.o.d -MD -MP tif_dir.c
gcc -c -o tif_dirinfo.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_dirinfo.o -MFtif_dirinfo.o.d -MD -MP tif_dirinfo.c
gcc -c -o tif_dirread.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_dirread.o -MFtif_dirread.o.d -MD -MP tif_dirread.c
gcc -c -o tif_dirwrite.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_dirwrite.o -MFtif_dirwrite.o.d -MD -MP tif_dirwrite.c
gcc -c -o tif_dumpmode.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_dumpmode.o -MFtif_dumpmode.o.d -MD -MP tif_dumpmode.c
gcc -c -o tif_error.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_error.o -MFtif_error.o.d -MD -MP tif_error.c
gcc -c -o tif_extension.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_extension.o -MFtif_extension.o.d -MD -MP tif_extension.c
gcc -c -o tif_fax3.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_fax3.o -MFtif_fax3.o.d -MD -MP tif_fax3.c
gcc -c -o tif_fax3sm.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_fax3sm.o -MFtif_fax3sm.o.d -MD -MP tif_fax3sm.c
gcc -c -o tif_flush.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_flush.o -MFtif_flush.o.d -MD -MP tif_flush.c
gcc -c -o tif_getimage.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_getimage.o -MFtif_getimage.o.d -MD -MP tif_getimage.c
gcc -c -o tif_jbig.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_jbig.o -MFtif_jbig.o.d -MD -MP tif_jbig.c
gcc -c -o tif_jpeg.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_jpeg.o -MFtif_jpeg.o.d -MD -MP tif_jpeg.c
gcc -c -o tif_jpeg_12.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_jpeg_12.o -MFtif_jpeg_12.o.d -MD -MP tif_jpeg_12.c
gcc -c -o tif_luv.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_luv.o -MFtif_luv.o.d -MD -MP tif_luv.c
gcc -c -o tif_lzma.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_lzma.o -MFtif_lzma.o.d -MD -MP tif_lzma.c
gcc -c -o tif_lzw.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_lzw.o -MFtif_lzw.o.d -MD -MP tif_lzw.c
gcc -c -o tif_next.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_next.o -MFtif_next.o.d -MD -MP tif_next.c
gcc -c -o tif_ojpeg.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_ojpeg.o -MFtif_ojpeg.o.d -MD -MP tif_ojpeg.c
gcc -c -o tif_open.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_open.o -MFtif_open.o.d -MD -MP tif_open.c
gcc -c -o tif_packbits.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_packbits.o -MFtif_packbits.o.d -MD -MP tif_packbits.c
gcc -c -o tif_pixarlog.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_pixarlog.o -MFtif_pixarlog.o.d -MD -MP tif_pixarlog.c
gcc -c -o tif_predict.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_predict.o -MFtif_predict.o.d -MD -MP tif_predict.c
gcc -c -o tif_print.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_print.o -MFtif_print.o.d -MD -MP tif_print.c
gcc -c -o tif_read.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_read.o -MFtif_read.o.d -MD -MP tif_read.c
gcc -c -o tif_strip.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_strip.o -MFtif_strip.o.d -MD -MP tif_strip.c
gcc -c -o tif_swab.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_swab.o -MFtif_swab.o.d -MD -MP tif_swab.c
gcc -c -o tif_thunder.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_thunder.o -MFtif_thunder.o.d -MD -MP tif_thunder.c
gcc -c -o tif_tile.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_tile.o -MFtif_tile.o.d -MD -MP tif_tile.c
gcc -c -o tif_version.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_version.o -MFtif_version.o.d -MD -MP tif_version.c
gcc -c -o tif_warning.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_warning.o -MFtif_warning.o.d -MD -MP tif_warning.c
gcc -c -o tif_write.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_write.o -MFtif_write.o.d -MD -MP tif_write.c
gcc -c -o tif_zip.o -g -O0 -mthreads  -DHAVE_W32API_H -DNDEBUG -I..\zlib -I..\jpeg -I..\libtiff   -MTtif_zip.o -MFtif_zip.o.d -MD -MP tif_zip.c